# Development overrides

services:
  caddy:
    build: ./caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports: !override
      - 8000:80
    environment:
      CADDY_SITE_ADDRESS: :80

  postgrest-trusted:
    environment:
      PGRST_DB_URI: postgres://authenticator:${PGRST_AUTHENTICATOR_PASS:?}@host.docker.internal:5432/myapp
      PGRST_LOG_LEVEL: debug

  postgrest-untrusted:
    environment:
      PGRST_DB_URI: postgres://authenticator:${PGRST_AUTHENTICATOR_PASS:?}@host.docker.internal:5432/myapp
      PGRST_LOG_LEVEL: debug
