services:
  postgres:
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./postgres/bin:/superstack-bin
      - ./postgres/migrations:/migrations
  caddy:
    volumes:
      - ./caddy/conf/Caddyfile:/etc/caddy/Caddyfile:ro
