services:
  postgres:
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro

  sqitch:
    volumes:
      - ./migrations:/repo:rw
      - ../sqitch-templates:/etc/sqitch/templates:ro
    environment:
      BASH_ENV: /etc/sqitch/templates/aliases.sh
      SQITCH_TARGET: postgres://${PG_USER}:${PG_PASS}@postgres:5432/app

  caddy:
    volumes:
      - ./caddy/conf:/etc/caddy:ro
    environment:
      - CADDY_AUTO_HTTPS=off
