services:
  iko:
    tty: true
    stdin_open: true
    volumes:
      - ./migrations:/repo:rw
      - ./scripts:/scripts:ro
    command: >
      /bin/sh -c '
        set -e
        if [ ! -f /repo/.sqitch-initialised ]; then
          sqitch init --target=postgres://${PG_USER}:${PG_PASS}@postgres:5432/app myapp
          bash /scripts/postgrest-init.sh
          sqitch deploy --verify
          touch /repo/.sqitch-initialised
        fi
      '

  caddy:
    volumes:
      - ./caddy/conf:/etc/caddy:ro
    environment:
      - CADDY_AUTO_HTTPS=off
