services:
  iko:
    tty: true
    stdin_open: true
    volumes:
      - ./migrations:/repo:rw
      - ./scripts:/scripts:ro
    environment:
      SQITCH_TARGET: postgres://${PG_USER}:${PG_PASS}@postgres:5432/app

  caddy:
    volumes:
      - ./caddy/conf:/etc/caddy:ro
    environment:
      - CADDY_AUTO_HTTPS=off
