site_name: SuperStack
site_url: https://explodinglabs.com/superstack/
repo_url: https://github.com/explodinglabs/superstack
theme:
  name: material
  features:
    - navigation.footer
    - palette.toggle
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: "blue"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "blue"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "blue"
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - Scripting: scripting.md
