# Development-only overrides

services:
  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      CADDY_SITE_ADDRESS: :80

  postgrest:
    environment:
      PGRST_LOG_LEVEL: debug
